# Generated by Django 4.0.2 on 2022-02-13 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
